import React from 'react'
export const metadata = {
    title: `Todas as Musicas`,
    description: "Generated by create next app",
  };
const page = () => {
  return (
    <div>
      <h1>Musicas</h1>
    </div>
  )
}

export default page
